### ISSUE TITLE
Should `Serial` not implement `PartialEq, Eq`?

### ISSUE THREAD

**Issue by timwie** [timwie/serial-num#3]
As a follow up to #1, I wonder if `Serial` should actually implement `PartialEq, Eq`.

In this case there seems to be no logic error in the traits' docs, but `==` might be misleading in the same way a comparison like `>` was before. Two `Serials` may be equal because their internal `u16` counters are, but semantically one might actually be the other's 65535th successor.  It might be a good idea to add inherent `eq()` and `ne()` methods to `Serial`, and remind users about that fact in their docs.

**Comment by timwie** [comment]
A big downside is not being able to have `HashSets` of `Serials`, as well as not being able to use them as keys in `HashMaps`. Not implementing `Ord` already rules out `BTreeSet` and `BTreeMap`.

When using `Serials` as packet sequence numbers, you would definitely want to store them in a set for acks. That means there would at least need to be some sort of `SerialSet` provided by the crate.

**Comment by kennytm** [comment]
I think implementing PartialEq is fine. Documentation is enough. As quoted in the documentation of [`std::cmp::Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html) for Serial `1` and `65536` and `131071` etc form an *equivalent class* and `==` here represent an [equivalent relation](https://en.wikipedia.org/wiki/Equivalence_relation).

**Comment by timwie** [comment]
Thanks @kennytm for your input, it's much appreciated!

It would also simply be too inconvenient. Still a question worth asking.

I'll close this one.
